# Generated by Django 5.2.6 on 2025-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='regular_holiday',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ward',
            field=models.CharField(blank=True, choices=[('CHIKUSA', '千種区'), ('HIGASHI', '東区'), ('KITA', '北区'), ('NISHI', '西区'), ('NAKAMURA', '中村区'), ('NAKA', '中区'), ('SHOWA', '昭和区'), ('MIZUHO', '瑞穂区'), ('ATSUTA', '熱田区'), ('NAKAGAWA', '中川区'), ('MINATO', '港区'), ('MINAMI', '南区'), ('MORIYAMA', '守山区'), ('MIDORI', '緑区'), ('MEITO', '名東区'), ('TEMPAKU', '天白区')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(choices=[('NAGOYA', '名古屋市')], default='NAGOYA', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='prefecture',
            field=models.CharField(choices=[('hokkaido', '北海道'), ('aomori', '青森県'), ('iwate', '岩手県'), ('miyagi', '宮城県'), ('akita', '秋田県'), ('yamagata', '山形県'), ('fukushima', '福島県'), ('ibaraki', '茨城県'), ('tochigi', '栃木県'), ('gunma', '群馬県'), ('saitama', '埼玉県'), ('chiba', '千葉県'), ('tokyo', '東京都'), ('kanagawa', '神奈川県'), ('niigata', '新潟県'), ('toyama', '富山県'), ('ishikawa', '石川県'), ('fukui', '福井県'), ('yamanashi', '山梨県'), ('nagano', '長野県'), ('gifu', '岐阜県'), ('shizuoka', '静岡県'), ('aichi', '愛知県'), ('mie', '三重県'), ('shiga', '滋賀県'), ('kyoto', '京都府'), ('osaka', '大阪府'), ('hyogo', '兵庫県'), ('nara', '奈良県'), ('wakayama', '和歌山県'), ('tottori', '鳥取県'), ('shimane', '島根県'), ('okayama', '岡山県'), ('hiroshima', '広島県'), ('yamaguchi', '山口県'), ('tokushima', '徳島県'), ('kagawa', '香川県'), ('ehime', '愛媛県'), ('kochi', '高知県'), ('fukuoka', '福岡県'), ('saga', '佐賀県'), ('nagasaki', '長崎県'), ('kumamoto', '熊本県'), ('oita', '大分県'), ('miyazaki', '宮崎県'), ('kagoshima', '鹿児島県'), ('okinawa', '沖縄県')], default='aichi', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(choices=[('-1000', '～¥1,000'), ('1000-2000', '¥1,000～¥2,000'), ('2000-3000', '¥2,000～¥3,000'), ('3000-4999', '¥3,000～¥4,999'), ('5000-9999', '¥5,000～¥9,999'), ('10000-', '¥10,000～')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('city', 'NAGOYA'), _negated=True), models.Q(('city', 'NAGOYA'), ('ward__isnull', False), models.Q(('ward', ''), _negated=True)), _connector='OR'), name='ward_required_when_nagoya'),
        ),
    ]
